### ISSUE TITLE
[suggestion] - Add vlang builtin modules in snippets

### ISSUE THREAD

**Issue by Olyno** [nedpals/vscode-vlang#1]
# Description

In snippets of the extension, it would be awesome to get an auto completion with all modules of vlang, like ``os`` module.

**Type:** Suggestion

**Comment by nedpals** [comment]
It will be available soon. That's already available on the experiment fork i created (and buggy): https://github.com/nedpals/vscode-vlang-bliss

Please file this issue to https://github.com/vlang/vscode-vlang so we can track it as well :smiley:

**Comment by Olyno** [comment]
It seems that an issue already exist about it: vlang/vscode-vlang#40

I close this issue.
